spring:
  datasource:
    url: jdbc:mysql://localhost:3306/potato_spring?useSSL=false&serverTimezone=UTC
    username: gyuseong2
    password: spring_test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect